// ***************************** APPLICATIONS.JS ROUTES ***************************** */

// STEP 1 TEST: Creating a client & application
POST http://localhost:3000/applications/step1
Content-Type: application/json

{
    "firstName": "Hannah",
    "middleName": "Chua",
    "lastName": "Fong",
    "email": "hrf@gmail.com",
    "contactNo": "09260716958",
    "establishmentName": "",
    "address": "159-C Apo St.",
    "refClientNo": 0,
    "refFirstName": "Hannah8",
    "refMiddleName": "Chua",
    "refLastName": "Fong",
    "landmark": "Lourdes School, QC",
    "ownership": "leased",
    "connectionType": "Tapping"
}

###

// For STEP 2 TEST: Uploading Valid ID for new application, use Thunder Client/Insomnia/API testing clients for form data (json/text fields and file upload)
    // Form data found below:
    {
        "hasRepresentative": true, // Test both boolean values to check if updated status is correct
        "validId": "validid.png" // Should be uploaded as file
    }
###

// For STEP 2A TEST: Representative Details (if applicable), use Thunder Client/Insomnia/API testing clients for form data (json/text fields and file upload)
    // Form data found below:
    {
        "firstName": "Jane",
        "middleName": "G.",
        "lastName": "Doe",
        "email": "jgd@gmail.com",
        "contactNo": "09756365927",
        "relationship": "aunt",
        "validId": "janedoepassport.png" // Should be uploaded as file
    }

###

// STEP 3-1 TEST: Autogenerating & Downloading Application Form
// NOTE: To test automatic download feature, copy the route link to browser
GET http://localhost:3000/applications/step3-1/0

###

// STEP 3-2 TEST: Downloading of Customer Reminders Document
// NOTE: To test automatic download feature, copy the route link to browser
GET http://localhost:3000/applications/step3-2/0

###

// STEP 3-3 TEST: Autogenerating & Downloading Authorization Letter (if w/ representative)
// NOTE: To test automatic download feature, copy the route link to browser
GET http://localhost:3000/applications/step3-3/0

###

// STEP 5 PREREQUISITE: Add materials to database
POST http://localhost:3000/applications/addmaterials
Content-Type: application/json

{
    "connectionType": "Tapping",
    "materials": [{
        "name": "Elbow 3/4",
        "quantity": "3" 
    },
    {
        "name": "Elbow 1/2",
        "quantity": "1" 
    }]
}

###

// STEP 5 TEST: Display Needed Materials
GET http://localhost:3000/applications/step5/0

###

// STEP 6 TEST: Update Application Stage to Visitation Status
GET http://localhost:3000/applications/step6/0

###

// STEP 7 TEST: Update Application Stage to Installation Status
GET http://localhost:3000/applications/step7/0

// ***************************** END OF APPLICATIONS.JS ROUTES ***************************** */

###

// ***************************** ADMIN.JS ROUTES ***************************** */

// LOG IN TEST (Aless)
    // STEP 1 Prerequisite: Add Credentials
POST http://localhost:3000/admin/addcredentials
Content-Type: application/json

{
    "firstName": "Jane",
    "middleName": "G.",
    "lastName": "Doe",
    "contactNo": "09260716958",
    "email": "jgd@swsi.com",
    "username": "swsidoej",
    "password": "J@n3d0e123"
}

###

    // STEP 1: Login
POST http://localhost:3000/admin/login
Content-Type: application/json

{
    "username": "swsidoej",
    "password": "J@n3d0e123"
}

###

    // STEP 1 BONUS: Logout
POST http://localhost:3000/admin/logout

###

// STEP 2 TEST: Display details for one application entry
GET http://localhost:3000/admin/applications/0

###

// STEP 2A TEST: Download Valid ID based on link on details page
GET http://localhost:3000/admin/applications/0/validid.png

###

// ADMIN DASHBOARD TEST (Hannah)
    // See all applications
GET http://localhost:3000/admin/applications

###

// APPLICATION DETAILS TEST (Aless)
    // Updating status and creating Update db entry
PATCH http://localhost:3000/admin/updatestatus/0
Content-Type: application/json

{
    "newStatus": "Completed"
}


// uploading-requirements
// adding-representative
// printing-and-preparing-documents
// waiting-for-survey-schedule
// pending-surveyor-visit
// purchasing-of-materials
// pending-onsite-visit
// pending-installation

###


// HANNAH TEST:

POST http://localhost:3000/applications/step1
Content-Type: application/json

{
    "firstName": "Hannah",
    "middleName": "Chua",
    "lastName": "Fong",
    "email": "reg",
    "contactNo": "09260716958",
    "establishmentName": "",
    "address": "11",
    "refClientNo": 0,
    "refFirstName": "Aless",
    "refMiddleName": "Interino",
    "refLastName": "Gomez",
    "landmark": "Lourdes",
    "ownership": "leased",
    "connectionType": "Tapping",
    "applicationStage": "adding-representative"
}

###

GET http://localhost:3000/admin/hello

###

GET http://localhost:3000/admin/surveySchedule/1?date=2021-12-12&time=14:10

###
GET http://localhost:3000/applications/0