GET http://localhost:3000/applications

###

GET http://localhost:3000/applications/634d902d295b5dcd5bb4ba6c

###

POST http://localhost:3000/applications
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

### 

DELETE http://localhost:3000/applications/634d902d295b5dcd5bb4ba6c

###
PATCH http://localhost:3000/applications/634d92c602df8404c52aad36
Content-Type: application/json

{
    "name": "New Name"
}

###
POST http://localhost:3000/applications
Content-Type: application/json

{
    "firstName": "Aless",
    "middleName": "Interino",
    "lastName": "Gomez",
    "email": "hrf@gmail.com",
    "contactNo": "09260716958",
    "establishmentName": "",
    "address": "159-C Apo St.",
    "refClientNo": 0,
    "refFirstName": "Hannah",
    "refMiddleName": "Chua",
    "refLastName": "Fong",
    "landmark": "Lourdes School, QC",
    "ownership": "owned"
}

###

POST http://localhost:3000/applications/submitID
Content-Type: application/json

{
    "name": "gomezLicense.jpg"
}

###

POST http://localhost:3000/applications/createRep
Content-Type: application/json

{
    "firstName": "Jane",
    "middleName": "G.",
    "lastName": "Doe",
    "email": "jgd@gmail.com",
    "contactNo": "09756365927",
    "relationship": "aunt",
    "validId": "janedoepassport.jpg"
}